[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "22.3.0"

[[plugins]]
  package = "@netlify/plugin-lighthouse"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
