[build]
  command = "npm install -g vite && npm --prefix frontend run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "22.3.0"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
